env:
  - EXTRA_DEPENDENCIES=pytorch,tensorflow
  # - EXTRA_DEPENDENCIES=pytorch
  # tests need both pytorch and tensorflow as they check they agree mathematically
  # TODO add skip option for tests so I can consider single build versions
language: python
python:
  - "3.7"  # tf 2.8 requires Python 3.7 and above
# command to install dependencies
install:
# let's check all three permutations resolve/install okay
  - pip install .[$EXTRA_DEPENDENCIES]
  
# command to run tests
script:
  - pytest

  # see https://docs.travis-ci.com/user/languages/python/
