version: '3'

services:
  zoobot:
    build:
      context:  ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/zoobot
      - /Users/camallen/workspace/zooniverse/kade/tmp/storage/staging/:/usr/src/zoobot/data/kade/
  zoobot_tf:
    build:
      context:  ./
      dockerfile: Dockerfile.tf
    volumes:
      - ./:/usr/src/zoobot
      - /Users/camallen/workspace/zooniverse/kade/tmp/storage/staging/:/usr/src/zoobot/data/kade/


