version: '3'

services:
  zoobot:
    build:
      context:  ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/zoobot
  zoobot_tf:
    build:
      context:  ./
      dockerfile: Dockerfile.tf
    volumes:
      - ./:/usr/src/zoobot

# example - you will need to update the attached volumes for your own machine
